language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - android-26
    - build-tools-26.0.2
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
      - android-sdk-preview-license-.+
      - android-sdk-license-.+
      - google-gdk-license-.+

before_install:
  - echo yes | android update sdk --all --filter build-tools-24.0.1 --no-ui --force

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - ./gradlew clean test